
[loot]
	#List of entity IDs that should trigger loot voting (example: minecraft:warden)
	loot_entities = ["minecraft:warden", "minecraft:zombie", "minecraft:cow", "minecraft:pig"]

	[loot.vote]
		#Radius (in blocks) around the entity in which players can vote (default: 100)
		vote_radius = 100
		#Duration of the vote session in seconds (default: 30)
		vote_duration = 30

